In [1]:
import pandas as pd
import datetime as dt

In [2]:
#Bring in original sample from CSV
df=pd.read_csv("./US_Accidents_June20.csv")
df.head(5)

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,MapQuest,201.0,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,MapQuest,201.0,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,MapQuest,201.0,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,MapQuest,201.0,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,MapQuest,201.0,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day

In [3]:
df.isnull().sum()

ID                             0
Source                         0
TMC                      1034799
Severity                       0
Start_Time                     0
End_Time                       0
Start_Lat                      0
Start_Lng                      0
End_Lat                  2478818
End_Lng                  2478818
Distance(mi)                   0
Description                    1
Number                   2262864
Street                         0
Side                           0
City                         112
County                         0
State                          0
Zipcode                     1069
Country                        0
Timezone                    3880
Airport_Code                6758
Weather_Timestamp          43323
Temperature(F)             65732
Wind_Chill(F)            1868249
Humidity(%)                69687
Pressure(in)               55882
Visibility(mi)             75856
Wind_Direction             58874
Wind_Speed(mph)           454609
Precipitation(in)        2025874
Weather_Condition          76138
Amenity                        0
Bump                           0
Crossing                       0
Give_Way                       0
Junction                       0
No_Exit                        0
Railway                        0
Roundabout                     0
Station                        0
Stop                           0
Traffic_Calming                0
Traffic_Signal                 0
Turning_Loop                   0
Sunrise_Sunset               115
Civil_Twilight               115
Nautical_Twilight            115
Astronomical_Twilight        115
dtype: int64

In [4]:
#Drop columns with signifiant amounts of null values
df_new=df.drop(['TMC', 'End_Lat', 'End_Lng', 'Number', 'Wind_Chill(F)', 'Precipitation(in)'], axis=1)
df_new

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Description,Street,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,MapQuest,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,0.010,Right lane blocked due to accident on I-70 Eas...,I-70 E,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,MapQuest,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,0.010,Accident on Brice Rd at Tussing Rd. Expect del...,Brice Rd,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,MapQuest,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,0.010,Accident on OH-32 State Route 32 Westbound at ...,State Route 32,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,MapQuest,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,0.010,Accident on I-75 Southbound at Exits 52 52B US...,I-75 S,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,MapQuest,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,0.010,Accident on McEwen Rd at OH-725 Miamisburg Cen...,Miamisburg Centerville Rd,...,False,False,False,False,True,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3513612,A-3513776,Bing,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379360,0.543,At Market St - Accident.,Pomona Fwy E,...,False,False,False,False,False,False,Day,Day,Day,Day
3513613,A-3513777,Bing,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148060,0.338,At Camino Del Rio/Mission Center Rd - Accident.,I-8 W,...,False,False,False,False,False,False,Day,Day,Day,Day
3513614,A-3513778,Bing,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775450,-117.847790,0.561,At Glassell St/Grand Ave - Accident. in the ri...,Garden Grove Fwy,...,False,False,False,False,False,False,Day,Day,Day,Day
3513615,A-3513779,Bing,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992460,-118.403020,0.772,At CA-90/Marina Fwy/Jefferson Blvd - Accident.,San Diego Fwy S,...,False,False,False,False,False,False,Day,Day,Day,Day
3513616,A-3513780,Bing,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230920,0.537,At Highland Ave/Arden Ave - Accident.,CA-210 W,...,False,False,False,False,False,False,Day,Day,Day,Day

In [5]:
df_new.isnull().sum()

ID                            0
Source                        0
Severity                      0
Start_Time                    0
End_Time                      0
Start_Lat                     0
Start_Lng                     0
Distance(mi)                  0
Description                   1
Street                        0
Side                          0
City                        112
County                        0
State                         0
Zipcode                    1069
Country                       0
Timezone                   3880
Airport_Code               6758
Weather_Timestamp         43323
Temperature(F)            65732
Humidity(%)               69687
Pressure(in)              55882
Visibility(mi)            75856
Wind_Direction            58874
Wind_Speed(mph)          454609
Weather_Condition         76138
Amenity                       0
Bump                          0
Crossing                      0
Give_Way                      0
Junction                      0
No_Exit                       0
Railway                       0
Roundabout                    0
Station                       0
Stop                          0
Traffic_Calming               0
Traffic_Signal                0
Turning_Loop                  0
Sunrise_Sunset              115
Civil_Twilight              115
Nautical_Twilight           115
Astronomical_Twilight       115
dtype: int64

In [6]:
#Drop rows with null values
df_clean=df_new.dropna()
df_clean

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Description,Street,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
2,A-3,MapQuest,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,0.010,Accident on OH-32 State Route 32 Westbound at ...,State Route 32,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,MapQuest,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,0.010,Accident on I-75 Southbound at Exits 52 52B US...,I-75 S,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,MapQuest,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,0.010,Accident on McEwen Rd at OH-725 Miamisburg Cen...,Miamisburg Centerville Rd,...,False,False,False,False,True,False,Day,Day,Day,Day
5,A-6,MapQuest,3,2016-02-08 07:44:26,2016-02-08 08:14:26,40.100590,-82.925194,0.010,Accident on I-270 Outerbelt Northbound near Ex...,Westerville Rd,...,False,False,False,False,False,False,Day,Day,Day,Day
6,A-7,MapQuest,2,2016-02-08 07:59:35,2016-02-08 08:29:35,39.758274,-84.230507,0.000,Accident on Oakridge Dr at Woodward Ave. Expec...,N Woodward Ave,...,False,False,False,False,False,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3513612,A-3513776,Bing,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379360,0.543,At Market St - Accident.,Pomona Fwy E,...,False,False,False,False,False,False,Day,Day,Day,Day
3513613,A-3513777,Bing,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148060,0.338,At Camino Del Rio/Mission Center Rd - Accident.,I-8 W,...,False,False,False,False,False,False,Day,Day,Day,Day
3513614,A-3513778,Bing,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775450,-117.847790,0.561,At Glassell St/Grand Ave - Accident. in the ri...,Garden Grove Fwy,...,False,False,False,False,False,False,Day,Day,Day,Day
3513615,A-3513779,Bing,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992460,-118.403020,0.772,At CA-90/Marina Fwy/Jefferson Blvd - Accident.,San Diego Fwy S,...,False,False,False,False,False,False,Day,Day,Day,Day
3513616,A-3513780,Bing,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230920,0.537,At Highland Ave/Arden Ave - Accident.,CA-210 W,...,False,False,False,False,False,False,Day,Day,Day,Day

In [7]:
df_clean.isnull().sum()

ID                       0
Source                   0
Severity                 0
Start_Time               0
End_Time                 0
Start_Lat                0
Start_Lng                0
Distance(mi)             0
Description              0
Street                   0
Side                     0
City                     0
County                   0
State                    0
Zipcode                  0
Country                  0
Timezone                 0
Airport_Code             0
Weather_Timestamp        0
Temperature(F)           0
Humidity(%)              0
Pressure(in)             0
Visibility(mi)           0
Wind_Direction           0
Wind_Speed(mph)          0
Weather_Condition        0
Amenity                  0
Bump                     0
Crossing                 0
Give_Way                 0
Junction                 0
No_Exit                  0
Railway                  0
Roundabout               0
Station                  0
Stop                     0
Traffic_Calming          0
Traffic_Signal           0
Turning_Loop             0
Sunrise_Sunset           0
Civil_Twilight           0
Nautical_Twilight        0
Astronomical_Twilight    0
dtype: int64

In [8]:
df_clean.dtypes

ID                        object
Source                    object
Severity                   int64
Start_Time                object
End_Time                  object
Start_Lat                float64
Start_Lng                float64
Distance(mi)             float64
Description               object
Street                    object
Side                      object
City                      object
County                    object
State                     object
Zipcode                   object
Country                   object
Timezone                  object
Airport_Code              object
Weather_Timestamp         object
Temperature(F)           float64
Humidity(%)              float64
Pressure(in)             float64
Visibility(mi)           float64
Wind_Direction            object
Wind_Speed(mph)          float64
Weather_Condition         object
Amenity                     bool
Bump                        bool
Crossing                    bool
Give_Way                    bool
Junction                    bool
No_Exit                     bool
Railway                     bool
Roundabout                  bool
Station                     bool
Stop                        bool
Traffic_Calming             bool
Traffic_Signal              bool
Turning_Loop                bool
Sunrise_Sunset            object
Civil_Twilight            object
Nautical_Twilight         object
Astronomical_Twilight     object
dtype: object

In [9]:
#Select 500k sample rows
df_sample = df_clean.sample(n = 500000)
df_sample

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Description,Street,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
3490633,A-3490797,Bing,2,2019-07-05 10:41:00,2019-07-05 11:39:00,40.816990,-111.918890,0.333,At US-89/Exit 312 - Accident.,I-15 N,...,False,False,False,False,False,False,Day,Day,Day,Day
1485927,A-1485959,MapQuest,3,2018-12-28 08:27:18,2018-12-28 08:56:49,30.502701,-87.229202,0.110,Accident on entry ramp to I-10 Eastbound at Ex...,I-110 N,...,False,False,False,False,False,False,Day,Day,Day,Day
2950422,A-2950571,Bing,2,2020-01-07 13:58:19,2020-01-07 14:27:03,37.558680,-79.658740,0.802,Between US-11/Exit 175 and US-11/Exit 167 - Ac...,I-81 S,...,False,False,False,False,False,False,Day,Day,Day,Day
153637,A-153639,MapQuest,2,2016-09-26 08:08:03,2016-09-26 08:37:07,33.832123,-84.335274,0.000,Accident on GA-42 Druid Hills Rd both ways at ...,GA-403 N,...,False,False,False,False,False,False,Day,Day,Day,Day
107913,A-107915,MapQuest,3,2016-05-19 22:08:20,2016-05-19 22:38:20,33.916611,-118.191299,0.000,Accident on I-105 Eastbound at Exit 12 Long Be...,I-105 E,...,False,False,False,False,False,False,Night,Night,Night,Night
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1383866,A-1383897,MapQuest,2,2019-01-04 13:20:04,2019-01-04 14:04:52,34.808762,-80.707916,0.000,Accident on Kirk Mccain Rd at Neill Rd.,Neill Rd,...,False,False,False,False,False,False,Day,Day,Day,Day
1113299,A-1113325,MapQuest,3,2019-06-12 08:03:30,2019-06-12 09:02:35,27.947500,-82.531822,11.640,2 right lane blocked due to accident on I-275 ...,I-275 N,...,False,False,False,False,False,False,Day,Day,Day,Day
1486192,A-1486224,MapQuest,2,2018-12-28 10:49:47,2018-12-28 11:34:33,33.538361,-112.073753,0.000,Accident on Central Ave at Glendale Ave.,W Glendale Ave,...,False,True,False,False,True,False,Day,Day,Day,Day
2293957,A-2293997,MapQuest,2,2017-10-06 14:56:55,2017-10-06 15:56:35,41.902390,-71.355820,0.000,Accident on MA-1A Newport Ave Northbound at I-95.,Newport Ave,...,False,False,False,False,False,False,Day,Day,Day,Day
81502,A-81504,MapQuest,2,2016-10-04 16:05:05,2016-10-04 16:35:05,34.432938,-119.793167,0.000,Accident on Ashton St Westbound at Inwood Dr.,Ashton St,...,False,False,False,False,False,False,Day,Day,Day,Day

In [10]:
df_sample.to_csv(r'C:\BootcampUCB\Final Project\df_sample_full.csv', index = True)

In [12]:
pd.set_option('display.max_columns', None)
df_sample.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Description,Street,Side,City,County,State,Zipcode,Country,Timezone,Airport_Code,Weather_Timestamp,Temperature(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
3490633,A-3490797,Bing,2,2019-07-05 10:41:00,2019-07-05 11:39:00,40.816990,-111.918890,0.333,At US-89/Exit 312 - Accident.,I-15 N,R,Salt Lake City,Salt Lake,UT,84116,US,US/Mountain,KSLC,2019-07-05 10:54:00,72.0,48.0,25.87,10.0,NW,9.0,Fair,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day
1485927,A-1485959,MapQuest,3,2018-12-28 08:27:18,2018-12-28 08:56:49,30.502701,-87.229202,0.110,Accident on entry ramp to I-10 Eastbound at Ex...,I-110 N,R,Pensacola,Escambia,FL,32504,US,US/Central,KPNS,2018-12-28 08:33:00,64.9,90.0,30.03,7.0,NNW,10.4,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
2950422,A-2950571,Bing,2,2020-01-07 13:58:19,2020-01-07 14:27:03,37.558680,-79.658740,0.802,Between US-11/Exit 175 and US-11/Exit 167 - Ac...,I-81 S,R,Buchanan,Botetourt,VA,24066,US,US/Eastern,KROA,2020-01-07 13:54:00,36.0,86.0,28.62,10.0,W,7.0,Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
153637,A-153639,MapQuest,2,2016-09-26 08:08:03,2016-09-26 08:37:07,33.832123,-84.335274,0.000,Accident on GA-42 Druid Hills Rd both ways at ...,GA-403 N,R,Atlanta,DeKalb,GA,30329,US,US/Eastern,KPDK,2016-09-26 07:53:00,70.0,81.0,30.06,10.0,Variable,3.5,Partly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
107913,A-107915,MapQuest,3,2016-05-19 22:08:20,2016-05-19 22:38:20,33.916611,-118.191299,0.000,Accident on I-105 Eastbound at Exit 12 Long Be...,I-105 E,R,Lynwood,Los Angeles,CA,90262,US,US/Pacific,KHHR,2016-05-19 22:22:00,62.1,78.0,29.86,10.0,WSW,4.6,Overcast,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night

In [13]:
#Trim down number of columns
df_sample_trim=pd.DataFrame(
    data=df,columns=['ID', 'Severity','Start_Time', 'End_Time', 'State', 'Country', 'Visibility(mi)', 'Weather_Condition', 'Sunrise_Sunset', 'Civil_Twilight'],index=df_sample.index.copy())
df_sample_trim

,ID,Severity,Start_Time,End_Time,State,Country,Visibility(mi),Weather_Condition,Sunrise_Sunset,Civil_Twilight
3490633,A-3490797,2,2019-07-05 10:41:00,2019-07-05 11:39:00,UT,US,10.0,Fair,Day,Day
1485927,A-1485959,3,2018-12-28 08:27:18,2018-12-28 08:56:49,FL,US,7.0,Light Rain,Day,Day
2950422,A-2950571,2,2020-01-07 13:58:19,2020-01-07 14:27:03,VA,US,10.0,Cloudy,Day,Day
153637,A-153639,2,2016-09-26 08:08:03,2016-09-26 08:37:07,GA,US,10.0,Partly Cloudy,Day,Day
107913,A-107915,3,2016-05-19 22:08:20,2016-05-19 22:38:20,CA,US,10.0,Overcast,Night,Night
...,...,...,...,...,...,...,...,...,...,...
1383866,A-1383897,2,2019-01-04 13:20:04,2019-01-04 14:04:52,SC,US,2.5,Rain,Day,Day
1113299,A-1113325,3,2019-06-12 08:03:30,2019-06-12 09:02:35,FL,US,10.0,Partly Cloudy,Day,Day
1486192,A-1486224,2,2018-12-28 10:49:47,2018-12-28 11:34:33,AZ,US,10.0,Clear,Day,Day
2293957,A-2293997,2,2017-10-06 14:56:55,2017-10-06 15:56:35,MA,US,10.0,Scattered Clouds,Day,Day
81502,A-81504,2,2016-10-04 16:05:05,2016-10-04 16:35:05,CA,US,10.0,Clear,Day,Day

In [14]:
df_sample_trim.to_csv(r'C:\BootcampUCB\Final Project\df_sample_trim.csv', index = True)

In [15]:
#Bring in cleaned sample from CSV
df_edit_sample=pd.read_csv("./df_sample_trim.csv")
df_edit_sample

,Unnamed: 0,ID,Severity,Start_Time,End_Time,State,Country,Visibility(mi),Weather_Condition,Sunrise_Sunset,Civil_Twilight
0,3490633,A-3490797,2,2019-07-05 10:41:00,2019-07-05 11:39:00,UT,US,10.0,Fair,Day,Day
1,1485927,A-1485959,3,2018-12-28 08:27:18,2018-12-28 08:56:49,FL,US,7.0,Light Rain,Day,Day
2,2950422,A-2950571,2,2020-01-07 13:58:19,2020-01-07 14:27:03,VA,US,10.0,Cloudy,Day,Day
3,153637,A-153639,2,2016-09-26 08:08:03,2016-09-26 08:37:07,GA,US,10.0,Partly Cloudy,Day,Day
4,107913,A-107915,3,2016-05-19 22:08:20,2016-05-19 22:38:20,CA,US,10.0,Overcast,Night,Night
...,...,...,...,...,...,...,...,...,...,...,...
499995,1383866,A-1383897,2,2019-01-04 13:20:04,2019-01-04 14:04:52,SC,US,2.5,Rain,Day,Day
499996,1113299,A-1113325,3,2019-06-12 08:03:30,2019-06-12 09:02:35,FL,US,10.0,Partly Cloudy,Day,Day
499997,1486192,A-1486224,2,2018-12-28 10:49:47,2018-12-28 11:34:33,AZ,US,10.0,Clear,Day,Day
499998,2293957,A-2293997,2,2017-10-06 14:56:55,2017-10-06 15:56:35,MA,US,10.0,Scattered Clouds,Day,Day
499999,81502,A-81504,2,2016-10-04 16:05:05,2016-10-04 16:35:05,CA,US,10.0,Clear,Day,Day