In [1]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
import tensorflow as tf
import pandas as pd
import datetime as dt

In [2]:
Data = pd.read_csv('cleaned_Data.csv')

In [3]:
en_list = Data.dtypes[(Data.dtypes == "object") | (Data.dtypes == "bool")].index.tolist()

In [4]:

encoder = OneHotEncoder(sparse = False)
encode_df = pd.DataFrame(encoder.fit_transform(Data[en_list][:1000000]))

encode_df.columns = encoder.get_feature_names(en_list)
encode_df.head()

,Start_Time_01-00,Start_Time_01-01,Start_Time_01-02,Start_Time_01-03,Start_Time_01-04,Start_Time_01-05,Start_Time_01-06,Start_Time_01-07,Start_Time_01-08,Start_Time_01-09,...,Traffic_Signal_True,Turning_Loop_False,Sunrise_Sunset_Day,Sunrise_Sunset_Night,Civil_Twilight_Day,Civil_Twilight_Night,Nautical_Twilight_Day,Nautical_Twilight_Night,Astronomical_Twilight_Day,Astronomical_Twilight_Night
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [4]:
X = Data
y = Data['Severity']
Data.columns

Index(['Severity', 'Start_Time', 'Start_Lat', 'Start_Lng', 'Distance(mi)',
       'Side', 'City', 'County', 'State', 'Timezone', 'Temperature(F)',
       'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction',
       'Wind_Speed(mph)', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [5]:
# not using the whole dataset,because my computer can't handle it
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size = 250000,train_size = 1000000,random_state = 1, stratify = y)
X_train

,Severity,Start_Time,Start_Lat,Start_Lng,Distance(mi),Side,City,County,State,Timezone,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
3018817,2,08-00,44.132160,-123.050440,0.58,R,1000_3000,1000-8000,OR,US/Pacific,...,False,False,False,False,False,False,Night,Night,Night,Night
1046200,2,05-12,34.673290,-83.109894,0.00,R,1000_3000,1000-8000,SC,US/Eastern,...,False,False,False,False,False,False,Day,Day,Day,Day
1257119,3,01-09,37.731850,-122.419388,0.00,R,6000-15000,San Francisco,CA,US/Pacific,...,False,False,False,False,False,False,Day,Day,Day,Day
1288259,2,11-15,33.386051,-111.757385,1.13,R,3000-6000,Maricopa,AZ,US/Mountain,...,False,False,False,False,False,False,Day,Day,Day,Day
97365,2,11-10,28.499979,-81.396812,0.01,L,Orlando,Orange,FL,US/Eastern,...,False,True,False,False,False,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397267,3,07-08,32.743950,-96.815582,0.00,R,Dallas,Dallas,TX,US/Central,...,False,False,False,False,False,False,Day,Day,Day,Day
488370,2,03-05,26.526159,-80.173927,2.29,R,1000_3000,Palm Beach,FL,US/Eastern,...,False,False,False,False,False,False,Night,Night,Night,Night
1656240,2,05-10,34.222980,-84.710602,0.00,L,20_100,0-1000,GA,US/Eastern,...,False,False,True,False,False,False,Day,Day,Day,Day
954623,2,08-16,37.517471,-77.449593,0.00,L,Richmond,Richmond City,VA,US/Eastern,...,False,False,False,False,False,False,Day,Day,Day,Day
329527,3,04-06,26.655329,-80.069389,0.01,R,3000-6000,Palm Beach,FL,US/Eastern,...,False,False,False,False,False,False,Night,Night,Day,Day

In [6]:
encoder = OneHotEncoder(sparse = False)
encode_df = pd.DataFrame(encoder.fit_transform(X_train[en_list]),index = X_train.index)

encode_df.columns = encoder.get_feature_names(en_list)
encode_df.head()


encoder1 = OneHotEncoder(sparse = False)
encode_df_test = pd.DataFrame(encoder1.fit_transform(X_test[en_list]),index = X_test.index)

encode_df_test.columns = encoder1.get_feature_names(en_list)
encode_df

,Start_Time_01-00,Start_Time_01-01,Start_Time_01-02,Start_Time_01-03,Start_Time_01-04,Start_Time_01-05,Start_Time_01-06,Start_Time_01-07,Start_Time_01-08,Start_Time_01-09,...,Traffic_Signal_True,Turning_Loop_False,Sunrise_Sunset_Day,Sunrise_Sunset_Night,Civil_Twilight_Day,Civil_Twilight_Night,Nautical_Twilight_Day,Nautical_Twilight_Night,Astronomical_Twilight_Day,Astronomical_Twilight_Night
3018817,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
1046200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1257119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1288259,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
97365,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397267,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
488370,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
1656240,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
954623,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
329527,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0

In [7]:
X_train = X_train.merge(encode_df,left_index = True, right_index = True)
X_train.drop(columns = en_list,inplace = True)

X_test = X_test.merge(encode_df_test,left_index = True, right_index = True)
X_test.drop(columns = en_list,inplace = True)
X_train

,Severity,Start_Lat,Start_Lng,Distance(mi),Temperature(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Start_Time_01-00,...,Traffic_Signal_True,Turning_Loop_False,Sunrise_Sunset_Day,Sunrise_Sunset_Night,Civil_Twilight_Day,Civil_Twilight_Night,Nautical_Twilight_Day,Nautical_Twilight_Night,Astronomical_Twilight_Day,Astronomical_Twilight_Night
3018817,2,44.132160,-123.050440,0.58,65.0,84.0,29.71,10.0,7.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
1046200,2,34.673290,-83.109894,0.00,81.0,65.0,29.09,10.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1257119,3,37.731850,-122.419388,0.00,54.0,69.0,30.02,10.0,4.6,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1288259,2,33.386051,-111.757385,1.13,62.1,46.0,29.83,10.0,6.9,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
97365,2,28.499979,-81.396812,0.01,69.1,81.0,30.07,9.0,5.8,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397267,3,32.743950,-96.815582,0.00,71.1,96.0,29.95,10.0,8.1,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
488370,2,26.526159,-80.173927,2.29,72.0,68.0,30.27,10.0,12.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
1656240,2,34.222980,-84.710602,0.00,73.0,96.0,30.10,10.0,3.5,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
954623,2,37.517471,-77.449593,0.00,82.0,70.0,29.81,10.0,12.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
329527,3,26.655329,-80.069389,0.01,72.0,59.0,30.17,10.0,9.2,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0

In [8]:
sc = StandardScaler()
sc.fit(X_train)
X_train_sc = sc.transform(X_train)
X_test_sc = sc.transform(X_test)

In [16]:
X_train_df = pd.DataFrame(X_train_sc,columns =X_train.columns,index = X_train.index)
X_test_df = pd.DataFrame(X_test_sc,columns =X_test.columns, index = X_test.index)

In [38]:
# create target
y_train = X_train_df['Severity']
X_train_df.drop('Severity',1,inplace = True)
y_test = X_test_df['Severity']
X_test_df.drop('Severity',1,inplace = True)

In [ ]:
y_train.to_csv('y_train.csv',index = False)
X_train_df.to_csv('X_train.csv',index = False)
y_test.to_csv('y_test.csv',index = False)
X_test_df.to_csv('X_test.csv',index =False)

In [34]:
number_input_features = len(X_train_df1)
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 8)                 8000008
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 45
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 6
=================================================================
Total params: 8,000,059
Trainable params: 8,000,059
Non-trainable params: 0
_________________________________________________________________

In [35]:
nn.compile(loss="CategoricalCrossentropy", optimizer="adam", metrics=["accuracy"])

In [41]:
fit_model = nn.fit(X_train_df,y_train,epochs=100)

MemoryError: Unable to allocate 4.28 GiB for an array with shape (1000000, 575) and data type float64

,Severity,Start_Lat,Start_Lng,Distance(mi),Temperature(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Start_Time_01-00,...,Traffic_Signal_True,Turning_Loop_False,Sunrise_Sunset_Day,Sunrise_Sunset_Night,Civil_Twilight_Day,Civil_Twilight_Night,Nautical_Twilight_Day,Nautical_Twilight_Night,Astronomical_Twilight_Day,Astronomical_Twilight_Night
335901,2,41.750454,-88.040794,0.010,55.6,68.0,29.82,10.0,21.9,0.0,...,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1652893,3,36.765205,-81.833855,0.000,82.4,55.0,30.17,10.0,4.6,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
712624,2,44.945263,-93.400452,0.670,41.0,70.0,28.86,10.0,15.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2323794,4,39.822110,-83.167470,17.884,57.0,55.0,29.33,10.0,8.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
124883,2,41.238426,-95.975822,0.010,36.0,67.0,29.95,10.0,3.5,0.0,...,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2444306,2,38.481622,-121.422277,0.000,44.0,85.0,29.94,10.0,6.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
1383634,3,39.819839,-84.189087,0.000,66.9,100.0,30.09,3.0,5.8,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
1888434,2,43.018223,-76.134750,0.000,28.9,100.0,29.50,0.8,8.1,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1822201,2,42.371555,-88.051140,0.000,45.0,56.0,30.18,10.0,16.1,0.0,...,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
172868,3,40.845249,-73.914116,0.000,70.0,65.0,30.20,10.0,8.1,0.0,...,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0